### ISSUE TITLE
Update the Exoplayer version

### ISSUE THREAD

**Issue by tulaune** [kishansinghpanwar/AutoPlayer#2]
not working with my version exoplayer: 2.16.1

**Comment by kishansinghpanwar** [comment]
@tulaune  As I can check this is working well with the `exoplayer 2.9.3`, 
I'm working on the new updates and for provide more options to customize the settings of player.
Soon I'll update the version, till then you can use the `v1.0.0` of AutoPlayer and if you are facing any issue in existing version let me know with full details. 
Thanks
