### ISSUE TITLE
Video not resume while pause video and scroll list.

### ISSUE THREAD

**Issue by Neerav006** [kishansinghpanwar/AutoPlayer#3]
Video not playing again after pause video and scroll list and again go to that video position. It only shows placeholder.Can you resolve this.

**Comment by kishansinghpanwar** [comment]
Hello @Neerav006, Thanks for raising the issue. 

But as I've checked the behaviour of _"Video not playing again after pause video and scroll list and again go to that video position_" In that case, there is no issue like that, 
I recommend you to check this on the AutoPlayer default example and If still facing the same issue please upload a Video with steps of reproduce, your device information(where you are facing this issue) and Logs for investigating it more.   

Thanks
