### ISSUE TITLE
Scroll Listener

### ISSUE THREAD

**Issue by sulemankhan2022** [kishansinghpanwar/AutoPlayer#4]
I have a recyler view in app homepage and inside that recycler view i  have nested recycler view which is in horizontal direction,
Since i have 2 recycler view i am able to attach scroll listener to any one, is there any way i can attach scroll listener to both recycler view and pause scroll on horizontal and vertical scroll both.
Thanks

**Comment by kishansinghpanwar** [comment]
Hello @sulemankhan2022, At the moment this library only supports a single RecyclerView (Vertically) at a time.
same as mentioned in screenshots :
https://github.com/kishansinghpanwar/AutoPlayer/blob/master/Screenshots/screenshot-1.png

I'll think about adding support for Horizontal scroll as well. Thanks
