### ISSUE TITLE
Scroll bug

### ISSUE THREAD

**Issue by MrNouri** [kishansinghpanwar/AutoPlayer#6]
Hi, Thanks for this great lib. <br>
I have problem, please help me.<br>
When scroll on list, crashed application and show me this error : <br>

`2023-02-26 10:07:08.731 9155-9207/com.example.autoplayer E/BufferQueueProducer: [SurfaceView[com.example.autoplayer/com.example.autoplayer.MainActivity]#1(BLAST Consumer)1](id:23c300000001,api:0,p:-1,c:9155) detachBuffer: BufferQueue has no connected producer
2023-02-26 10:07:34.786 9155-9207/com.example.autoplayer E/BufferQueueProducer: [SurfaceView[com.example.autoplayer/com.example.autoplayer.MainActivity]#2(BLAST Consumer)2](id:23c300000002,api:0,p:-1,c:9155) detachBuffer: BufferQueue has no connected producer
2023-02-26 10:07:34.826 9155-9177/com.example.autoplayer A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 9177 (RenderThread), pid 9155 (mple.autoplayer)`

**Comment by kishansinghpanwar** [comment]
Hi @MrNouri, thanks for using this library.

Please provide some more details about the issue you're facing.

The crash occurs on which android version and which device is this?

The crash occurs with the default example code ?
If yes - let me know if you made any changes in the default example code.
If not - share the demo code where you are facing this crash. 

Any special environment (vpn, proxy) ? 

This is happening with specific url? 

Cache related settings was enabled or disabled?

**Comment by MrNouri** [comment]
Really great library, really. Thanks for develop this. <br>
When test on real device every things is ok. <br>
Can I play mp3 with this library?

**Comment by MrNouri** [comment]
Really great library, really. Thanks for develop this.

When test on real device every things is ok.

Can you update exo player to 2.18 ?

**Comment by kishansinghpanwar** [comment]
I'm working on the new updates along with more customization options for player.

I'll update the version soon, till then you can use the current version.

_If you found this library is helpful for you 🌟 this. Thanks_
